### ISSUE TITLE
How to use with sega contra hard cops 

### ISSUE THREAD

**Issue by salvadorc17** [spiiin/CadEditor#3]
I just try to load level, and it display only tileset, how to use and what can modify..

**Comment by spiiin** [comment]
You can edit layerA and layerB level maps and blocks (metatiles) for all levels with CadEditor, and view (read-only, because I have no decode all objects codes) all level objects. 

**To start CadEditor with one of game map**

There are many runCadEditorContra*.bat in settings_sega_contra_hard_corps folder for every level in game.
Run one of them or pass Config_*.cs parameter to CadEditor wia command line as it is written in the bat files – "start CadEditor.exe settings_sega_contra_hard_corps/Config_1.cs" for example. 

There are three important functions in this file:
1. getFileName – name of your Contra Hard Corps ROM file, it's not included in the repository.
2. getConfigName – settings file Settings_SegaContra_*.cs, this file show how data will be loaded from ROM and dump files)
3. getDumpName – dumped level map. It's separated from ROM file, because inside ROM level maps are compressed, so you need either rip it from RAM while game running in emulator, either rip original archives from ROM file and decompress it with [LZKN decompressor/decompressor](https://github.com/lab313ru/lzkn):
I put all decompressed archives to map_*.bin files, so you don't need to do this step manually.

**To put changed map inside game**
After editing level, you must compress map file back with [LZKN decompressor/decompressor](https://github.com/lab313ru/lzkn) and replace original archive inside ROM with your new archive.
I save offsets of original archive in Setting_SegaContra*.cs files, for example for 1st level:
[https://github.com/spiiin/CadEditor/blob/master/CadEditor/settings_sega_contra_hard_corps/Settings_SegaContra_1.cs#L55](https://github.com/spiiin/CadEditor/blob/master/CadEditor/settings_sega_contra_hard_corps/Settings_SegaContra_1.cs#L55)
`private string BLOCKS_NAME = "blocks_11.bin"; //1E391A//1E597C`
1E391A - offset for layerA archive
1E597C - offset for layerB archive

After this you can load game in emulator and view changed level.

**Comment by salvadorc17** [comment]
So it will be expanded to edit objects/events?? That is like most important..

**Comment by spiiin** [comment]
Maybe, but not soon

**Comment by spiiin** [comment]
Objects can be edited now (with a changing bytes in table, so you must know what exactly you doing). Also improved sega block editor and added recompressing plugin for inject maps back in ROM from CadEditor
https://github.com/spiiin/CadEditor/releases/tag/v4.6

video example in release notes
