### ISSUE TITLE
Проблема с ошибкой.

### ISSUE THREAD

**Issue by Agnyy** [spiiin/CadEditor#8]
Добрый день писал вам на почту, но вдруг у вас нет возможности её проверить, так что дублирую сюда.  

"Привет, очень интересная программа  CadEditor, но у меня она почему то не работает. Точнее не редактирует игры. Я безумно сильно хочу переделать игру детсва, но что то ни как. Может я просто что то делаю не так? я выбираю игры, потом выбираю CS фаил игры, 

![image](https://user-images.githubusercontent.com/25137502/41510009-d4b38576-7265-11e8-9cc3-7e56f4ab767d.png)

но при запуске.  Ошибка.

![image](https://user-images.githubusercontent.com/25137502/41510003-c164ab4e-7265-11e8-8a13-a84e8d131124.png)

 И ни как не могу найти решения. Я понимаю что я вас могу очень сильно отвлекать, просто желание переделать игру очень сильное. Я так долго искал хороший редактор, что найдя его уже не могу отпустить. Я кстати тоже работаю в опенсорс индустрии, но не программист, а куратор проекта"

**Comment by spiiin** [comment]
Скорее всего, ошибка заключается в том, что вы не разблокировали архив перед тем, как разархивировать файлы. Из-за этого все dll и exe файлы заблокированы windows как опасные (так помечаются вообще любые файлы, скачанные из интернета). Редактор загружает dll плагины во время запуска, и при этом возникает эта ошибка. В дальнейшем я надеюсь сделать инсталлятор приложения, который будет избавлен от этой проблемы.

Вот описание, как разблокировать архив с редактором перед разархивацией (из readme.md репозитория редактора):
Important: if you download release archive from github, you must unblock it for correct running EXE and DLL files https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/ More explanations: http://www.romhacking.net/forum/index.php?topic=17150.msg356786#msg356786 This will be fixed in future releases.

**Comment by spiiin** [comment]
Если есть возможность, проверьте мой инсталлятор редактора.
[CadEditorSetup50.zip](https://github.com/spiiin/CadEditor/files/2179195/CadEditorSetup50.zip)

По идее, после установки файлы должны быть разблокированы. Если этот метод сработает, я буду выкладывать основные релизы в виде инсталляторов

**Comment by Agnyy** [comment]
Проверил, всё работает ))
